'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const k = require('../kernel.cjs');
const rules = {quantityStep: 1, priceTick: .01, minQuantity: 1, minNotional: 0, maxQuantity: 0, maxNotional: 0};
const windows = k.sessionWindows('2026-10-05', '2026-10-09', 'XNYS'), start = windows[0].start, end = windows.at(-1).end;
const history = Array.from({length:21}, (_, i) => ({observedAt: start - (21-i)*k.DAY, availableAt: start - (21-i)*k.DAY, price:100*Math.exp(.01*(i%2))}));
function book(over={}) {return k.createBook({position: 0, target: 100, cash: 20000, startAt:start, rules, ...over});}
function config(over={}) {return {strategy:'paced_passive', deadlineAt:end, weeklyQuantity:60, weekStartAt:start-k.DAY, weekEndAt:end+k.DAY, passiveFeeBps:2, aggressiveFeeBps:5, aggressiveSlippageBps:5,...over};}
function market(over={}) {const now=over.now??start; return {now,nextReviewAt:now+60*k.MINUTE,windows,history,quote:{at:now,availableAt:now,mid:100,bid:99.99,ask:100.01},...over};}
function intent(over={}) {return {side:'buy',quantity:10,limitPrice:100,feeBps:10,kind:'passive_limit',...over};}
function submit(b=book(),o=intent(),id='o',at=start){return k.submit(b,o,id,at);}
test('target derives side and residual from holdings',()=>{assert.equal(k.plan(book({position:160,target:100}),config(),market()).side,'sell');assert.equal(k.plan(book({position:35,target:100}),config(),market()).remaining,65);});
test('target reached yields no order',()=>assert.equal(k.plan(book({position:100}),config(),market()).reason,'target_reached'));
test('strict step rejects fractional listed target and negative holdings',()=>{assert.throws(()=>book({target:100.5}),/aligned/);assert.throws(()=>book({position:-1}),/invalid/);});
test('cash reserve includes fee cap',()=>{const b=submit();assert.ok(Math.abs(k.reserves(b).cash-1001)<1e-8);assert.throws(()=>submit(book({cash:1000})),/resources/);});
test('reservation caps whole target and inventory',()=>{assert.throws(()=>submit(book(),intent({quantity:101})),/target/);assert.throws(()=>submit(book({position:100,target:0}),intent({side:'sell',quantity:101})),/resources/);});
test('opposite outstanding order fails closed',()=>assert.throws(()=>submit(book(),intent({side:'sell'})),/resources|opposite/));
test('partial fill conserves position cash and reserves',()=>{const b=k.applyFill(submit(),{id:'f',orderId:'o',quantity:4,price:99,feeBps:10,at:start+1});assert.equal(b.positionLots,4);assert.ok(Math.abs(b.cash-(20000-396.396))<1e-8);assert.ok(Math.abs(k.reserves(b).cash-600.6)<1e-8);assert.equal(k.residualLots(b),96);});
test('identical duplicate fill id is idempotent; conflicts rejected',()=>{const f={id:'f',orderId:'o',quantity:4,price:99,feeBps:10,at:start+1},b=k.applyFill(submit(),f);assert.deepEqual(k.applyFill(b,f),b);assert.throws(()=>k.applyFill(b,{...f,quantity:5}),/conflicting/);});
test('pending cancel retains reservation, fill race accepted, ack releases remaining',()=>{let b=k.cancelRequest(submit(),'o',start+1);assert.equal(k.reserves(b).targetLots,10);b=k.applyFill(b,{id:'f',orderId:'o',quantity:3,price:99,feeBps:10,at:start+2});assert.equal(k.reserves(b).targetLots,7);b=k.cancelAck(b,'o',start+3);assert.equal(k.reserves(b).targetLots,0);assert.equal(b.positionLots,3);});
test('late fill after terminal ack requires reconciliation',()=>{const b=k.cancelAck(k.cancelRequest(submit(),'o',start+1),'o',start+2);assert.throws(()=>k.applyFill(b,{id:'f',orderId:'o',quantity:3,price:99,feeBps:1,at:start+1}),/reconciliation/);});
test('fee above cap, overfill and worse price fail',()=>{const f={id:'f',orderId:'o',quantity:10,price:100,feeBps:10,at:start+1};assert.throws(()=>k.applyFill(submit(),{...f,feeBps:11}),/fee/);assert.throws(()=>k.applyFill(submit(),{...f,quantity:11}),/reconciliation/);assert.throws(()=>k.applyFill(submit(),{...f,price:101}),/price/);});
test('target change requires no outstanding orders and records new segment',()=>{assert.throws(()=>k.reviseTarget(submit(),50,start+2),/cancellation/);let b=k.applyFill(submit(),{id:'f',orderId:'o',quantity:10,price:100,feeBps:1,at:start+1});b=k.reviseTarget(b,5,start+2);assert.equal(b.initialTaskLots,5);assert.equal(b.fills.length,1);assert.equal(b.revisions.length,1);assert.equal(k.plan(b,config(),market({now:start+2})).side,'sell');});
test('weekly zero pauses without deadline',()=>assert.equal(k.plan(book(),config({deadlineAt:null,weeklyQuantity:0}),market()).allocated,0));
test('no deadline does not tighten or produce closeout',()=>{const a=k.plan(book(),config({deadlineAt:null}),market()),b=k.plan(book(),config({deadlineAt:null}),market({now:windows[4].start}));assert.equal(a.distanceFactor,1);assert.equal(b.distanceFactor,1);assert.equal(b.progress,null);assert.throws(()=>k.plan(book(),config({deadlineAt:null,manualCloseoutScenario:true}),market()),/outside/);});
test('GTC carried into next week subtracts from allowance',()=>{const b=submit(book(),intent({quantity:50}));const p=k.plan(b,config({deadlineAt:null,weeklyQuantity:60}),market());assert.equal(p.allocated,10);assert.equal(p.reserved,50);});
test('weekly fills and open orders are not double counted',()=>{let b=submit(book(),intent({quantity:40}));b=k.applyFill(b,{id:'f',orderId:'o',quantity:10,price:99,feeBps:1,at:start+1});const p=k.plan(b,config({deadlineAt:null}),market({now:start+2}));assert.equal(p.allocated,20);});
test('schedule uses immutable original task and trading minutes',()=>{let b=submit(book(),intent({quantity:20}));b=k.applyFill(b,{id:'f',orderId:'o',quantity:20,price:99,feeBps:1,at:start+1});const now=windows[2].start,p=k.plan(b,config(),market({now,nextReviewAt:windows[2].end}));assert.equal(p.scheduledQuantity,40);assert.equal(p.allocated,40);});
test('near deadline min-distance and explicit manual closeout',()=>{const now=end-15*k.MINUTE,p=k.plan(book(),config({manualCloseoutScenario:true}),market({now,nextReviewAt:end}));assert.equal(p.allocated,100);assert.ok(p.intents.every(o=>o.kind==='aggressive_scenario'));assert.equal(p.manualCloseoutRequired,true);});
test('manual closeout never duplicates pending-cancel quantity',()=>{const b=k.cancelRequest(submit(book(),intent({quantity:80})),'o',start+1),now=end-15*k.MINUTE,p=k.plan(b,config({manualCloseoutScenario:true}),market({now,nextReviewAt:end}));assert.equal(p.allocated,0);assert.equal(p.reason,'cancel_acknowledgments_required');assert.equal(p.reserved,80);});
test('deadline passed gives no orders',()=>{const now=windows[3].start,deadline=windows[2].end;assert.equal(k.plan(book(),config({deadlineAt:deadline}),market({now})).reason,'deadline_elapsed');});
test('unavailable and future data do not affect volatility or orders',()=>{const a=k.plan(book(),config(),market());const future={observedAt:start+1,availableAt:start+2,price:99999};const b=k.plan(book(),config(),market({history:[...history,future]}));assert.deepEqual(a,b);const delayed={observedAt:start-1,availableAt:start+1,price:1};assert.deepEqual(a,k.plan(book(),config(),market({history:[...history,delayed]})));});
test('volatility insufficient/duplicate data is explicit',()=>{assert.throws(()=>k.volatility(history.slice(1),start,100,.01),/21/);assert.throws(()=>k.volatility([...history,history[0]],start,100,.01),/duplicate/);});
test('stale/future quote rejects and closed sessions do not plan',()=>{assert.throws(()=>k.plan(book(),config(),market({quote:{at:start-61000,availableAt:start-61000,mid:100,bid:99,ask:101}})),/quote/);assert.throws(()=>k.plan(book(),config(),market({quote:{at:start+1,availableAt:start+1,mid:100,bid:99,ask:101}})),/quote/);assert.equal(k.plan(book(),config(),market({now:windows[0].end})).reason,'market_closed');});
test('early closes, holiday, weekend and DST handled in calendar',()=>{const w=k.sessionWindows('2026-11-26','2026-11-30','XNYS');assert.equal(w.length,2);assert.equal((w[0].end-w[0].start)/k.MINUTE,204);assert.equal(new Date(w[0].end).toISOString(),'2026-11-27T18:00:00.000Z');const dst=k.sessionWindows('2026-03-06','2026-03-09','XNYS');assert.equal(new Date(dst[0].start).getUTCHours(),14);assert.equal(new Date(dst[1].start).getUTCHours(),13);});
test('crypto is UTC every day and calendar unsupported fails closed',()=>{assert.equal(k.sessionWindows('2026-10-10','2026-10-11','24X7').length,2);assert.throws(()=>k.sessionWindows('2029-01-01','2029-01-02','XNYS'),/2025/);});
test('conservative rounding, min order, fee budget and sell cap',()=>{let p=k.plan(book({cash:100}),config({deadlineAt:null,weeklyQuantity:100}),market());assert.ok(p.intents.reduce((s,o)=>s+o.quantity*o.limitPrice*(1+o.feeBps/10000),0)<=100);p=k.plan(book({rules:{...rules,minNotional:100000}}),config(),market());assert.equal(p.allocated,0);const sell=k.plan(book({position:100,target:20}),config({deadlineAt:null}),market());assert.ok(sell.intents.every(o=>o.limitPrice>=100));});
test('immediate and baseline honor no-deadline weekly allowance',()=>{assert.equal(k.plan(book(),config({strategy:'immediate',deadlineAt:null}),market()).allocated,60);assert.throws(()=>k.plan(book(),config({strategy:'same_horizon_twap',deadlineAt:null}),market()),/timestamp/);const p=k.plan(book(),config({strategy:'same_horizon_twap',deadlineAt:null,comparisonHorizonAt:end}),market({nextReviewAt:windows[0].end}));assert.equal(p.allocated,12);});
test('minimum target scales correctly without claiming liquidity invariance',()=>{const b=book({position:.004,target:.005,rules:{...rules,quantityStep:.00001,minQuantity:.00001}}),p=k.plan(b,config({deadlineAt:null,weeklyQuantity:.001}),market());assert.ok(Math.abs(p.allocated-.001)<1e-12);});
test('all-target cost includes unfilled residual; no-fill cost still exists',()=>{const m=k.metrics(book(),100,110);assert.ok(Math.abs(m.costBps-1000)<1e-9);assert.equal(m.executedOnlyCostBps,null);assert.equal(m.completion,0);const s=k.metrics(book({position:100,target:0}),100,110);assert.ok(Math.abs(s.costBps+1000)<1e-9);});
test('buy and sell quantity cost use identical denominator including fees',()=>{let b=k.applyFill(submit(book(),intent({quantity:100})),{id:'f',orderId:'o',quantity:100,price:100,feeBps:10,at:start+1});assert.ok(Math.abs(k.metrics(b,100,100).costBps-10)<1e-8);let s=submit(book({position:100,target:0}),intent({side:'sell',quantity:100}));s=k.applyFill(s,{id:'f',orderId:'o',quantity:100,price:100,feeBps:10,at:start+1});assert.ok(Math.abs(k.metrics(s,100,100).costBps-10)<1e-8);});
test('pure planner does not mutate book and repeated planning matches',()=>{const b=book(),before=JSON.stringify(b);assert.deepEqual(k.plan(b,config(),market()),k.plan(b,config(),market()));assert.equal(JSON.stringify(b),before);});
test('future account state rejects planning',()=>{const b=submit(book(),intent(),'o',start+100);assert.throws(()=>k.plan(b,config(),market()),/future/);});

test('price-unit rescaling preserves dimensionless ladder within matched tick rules',()=>{const a=k.plan(book(),config(),market());const scaledBook=book({cash:200000,rules:{...rules,priceTick:.1}});const m=market();m.history=m.history.map(x=>({...x,price:x.price*10}));m.quote={...m.quote,mid:1000,bid:999.9,ask:1000.1};const b=k.plan(scaledBook,config(),m);assert.equal(a.intents.length,b.intents.length);a.intents.forEach((o,i)=>{assert.equal(o.quantity,b.intents[i].quantity);assert.ok(Math.abs(o.limitPrice*10-b.intents[i].limitPrice)<1e-8);});});

test('weekend deadline uses the last eligible close and exposes both timestamps',()=>{const ww=k.sessionWindows('2026-10-05','2026-10-11','XNYS'),requested=Date.parse('2026-10-11T23:59:00Z'),now=ww.at(-1).end-15*k.MINUTE;const p=k.plan(book(),config({deadlineAt:requested,manualCloseoutScenario:true}),market({now,nextReviewAt:ww.at(-1).end,windows:ww}));assert.equal(p.requestedDeadlineAt,requested);assert.equal(p.effectiveDeadlineAt,ww.at(-1).end);assert.equal(p.allocated,100);assert.equal(k.plan(book(),config({deadlineAt:requested}),market({now:ww.at(-1).end,windows:ww})).reason,'deadline_elapsed');});
test('holiday deadline resolves to prior half-day when that is last eligible session',()=>{const ww=k.sessionWindows('2026-12-24','2026-12-25','XNYS'),at=ww[0].start,deadline=Date.parse('2026-12-25T23:59:00Z');const b=book({startAt:at});const p=k.plan(b,config({deadlineAt:deadline,manualCloseoutScenario:true}),market({now:ww[0].end-15*k.MINUTE,nextReviewAt:ww[0].end,windows:ww}));assert.equal(new Date(p.effectiveDeadlineAt).toISOString(),'2026-12-24T18:00:00.000Z');assert.equal(p.allocated,100);});
