'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const replay=require('../replay.cjs'),spec=require('../spec.json');
const arg={seed:7,family:'flat',side:'buy',mode:'deadline',scenario:spec.scenarios[1],policy:'paced_hybrid_50'};
test('replay is deterministic and preserves scenario inputs',()=>{const before=JSON.stringify(arg);assert.deepEqual(replay.simulate(arg),replay.simulate(arg));assert.equal(JSON.stringify(arg),before);});
test('decision diagnostics reference only available history',()=>{const p=replay.simulate({...arg,trace:true});for(const t of p.traces){if(t.plan.volatility){assert.ok(t.plan.volatility.lastAvailableAt<=t.at);assert.ok(t.plan.volatility.lastObservedAt<=t.at);}}});
test('zero passive stress remains incomplete despite modeled closeout',()=>{const x=replay.simulate({...arg,scenario:spec.scenarios[2],policy:'paced_passive'});assert.equal(x.passiveCompletion,0);assert.equal(x.precloseoutResidual,100);assert.equal(x.manualCloseoutFraction,.1);assert.equal(x.completion,.1);});
test('no deadline never gets closeout and respects sixty-unit allowance',()=>{for(const policy of spec.policies){const x=replay.simulate({...arg,policy,mode:'no_deadline',scenario:spec.scenarios[0]});assert.equal(x.manualCloseoutFraction,0);assert.ok(x.completion<=.6000001);if(['same_horizon_twap','immediate'].includes(policy))assert.equal(x.completion,.6);}});
test('every buy/sell scenario policy yields finite cost and bounded completion',()=>{for(const scenario of spec.scenarios)for(const policy of spec.policies)for(const side of ['buy','sell'])for(const mode of ['deadline','no_deadline']){const x=replay.simulate({...arg,scenario,policy,side,mode});assert.ok(Number.isFinite(x.costBps));assert.ok(x.completion>=0&&x.completion<=1);assert.ok(x.passiveCompletion>=0&&x.passiveCompletion<=x.completion);assert.ok(x.aggressiveFraction>=0);assert.ok(Math.abs(x.passiveCompletion+x.aggressiveFraction-x.completion)<1e-9);assert.equal(x.reservedAtEnd,0);}});
test('closeout toggle changes completion without relabeling passive fills',()=>{const a=replay.simulate({...arg,policy:'paced_passive'}),b=replay.simulate({...arg,policy:'paced_passive',closeout:false});assert.equal(a.passiveCompletion,b.passiveCompletion);assert.ok(a.completion>=b.completion);assert.equal(a.precloseoutResidual,b.precloseoutResidual);});
test('same seed supplies identical market path independent of strategy or side',()=>{const xs=spec.policies.map(policy=>replay.simulate({...arg,policy}));assert.equal(new Set(xs.map(x=>x.terminal)).size,1);assert.equal(xs[0].terminal,replay.simulate({...arg,side:'sell'}).terminal);});

test('perturbing the future suffix preserves every prior decision',()=>{const original=replay.makePath(7,'flat','deadline'),changed=structuredClone(original);for(const bar of changed.bars.slice(12))for(const key of ['open','close','low','high'])bar[key]*=1.25;changed.terminal*=1.25;const a=replay.simulate({...arg,pathOverride:original,trace:true}),b=replay.simulate({...arg,pathOverride:changed,trace:true});assert.deepEqual(a.traces.slice(0,12),b.traces.slice(0,12));});
test('deterministic constant price exposes zero-fill versus paid-completion tradeoff',()=>{const p=replay.makePath(7,'flat','deadline');p.terminal=100;for(const b of p.bars)for(const key of ['open','close','low','high'])b[key]=100;for(const h of p.history)h.price=100;const passive=replay.simulate({...arg,policy:'paced_passive',pathOverride:p,closeout:false}),immediate=replay.simulate({...arg,policy:'immediate',pathOverride:p,closeout:false});assert.equal(passive.completion,0);assert.equal(passive.costBps,0);assert.equal(immediate.completion,1);assert.ok(immediate.costBps>0);});
test('normal final TWAP tranche completes without a manual rescue',()=>{for(const scenario of spec.scenarios){const x=replay.simulate({...arg,policy:'same_horizon_twap',scenario,closeout:false});assert.equal(x.completion,1);assert.equal(x.withoutManualCloseout.completion,1);assert.equal(x.manualCloseoutFraction,0);}});
